### ISSUE TITLE
Realtek RTL8195AM DAP firmware link unavailable 

### ISSUE THREAD

**Issue by gggekov** [ARMmbed/mbed-os-example-blinky#101]
The DAPLink firmware update link for the RTL8195AM(https://os.mbed.com/platforms/Realtek-RTL8195AM/) board is giving error 404. 

Furthermore, I can't register on the realtek website(https://www.amebaiot.com/wp-login.php?action=register). I am getting an error "ERROR: Couldn’t register you… please contact the webmaster !"

Can you please fix this issue?

Regards,
George

**Comment by adbridge** [comment]
@c1728p9 Any ideas ?

**Comment by MarceloSalazar** [comment]
@gggekov you need to register and login to be able to download the binary.
I've managed to do it and confirm works fine.
