### ISSUE TITLE
This GettingStarted.html generated by "mbed export" redirect to a broken documentation page

### ISSUE THREAD

**Issue by jamesbeyond** [ARMmbed/mbed-os-example-blinky#105]
I followed the guide to run "mbed export -m K64F -i uvision" command.
the mbed cli created a "GettingStarted.html" in my local working directory.
By double click on the HTML file, this redirect me to "https://os.mbed.com/docs/v5.6/tools/exporting.html/"
Which is not a very well formatted documentation page, and all the URL links on that page had broken

**Comment by MarceloSalazar** [comment]
@theotherjimmy please have a look

**Comment by 0xc0170** [comment]
@AnotherButler I can fix this if I know where it should point it (did the link changed) ?

**Comment by AnotherButler** [comment]
@0xc0170 The problem with that link is the slash at the end. https://os.mbed.com/docs/v5.6/tools/exporting.html formats correctly. If you delete the slash, I think it should be OK.

**Comment by 0xc0170** [comment]
Thanks, sending PR now :)

**Comment by 0xc0170** [comment]
This was fixed
