### ISSUE TITLE
mbed documentation does not include information on how to use a specific revision

### ISSUE THREAD

**Issue by cargro** [ARMmbed/mbed-os-example-blinky#116]
Follow instructions on 

https://os-doc-builder.test.mbed.com/docs/latest/tutorials/quick-start-online.html

Need to use 5.8 RC 2 for OOB test. 

Documentation needs to include instructions to import from URL:

![image](https://user-images.githubusercontent.com/36272895/37604090-18469078-2b88-11e8-823b-f646a17b822b.png)

The going to revisions, noting that current revision is shown in bold:

![image](https://user-images.githubusercontent.com/36272895/37604135-2f46430e-2b88-11e8-8615-16ba6b3a660f.png)

Select desired revision. Click Switch 

Correct revision should now be in bold:

![image](https://user-images.githubusercontent.com/36272895/37604173-4620d9a4-2b88-11e8-9189-732e5fbc6dbc.png)

**Comment by 0xc0170** [comment]
@AnotherButler Can you review?

**Comment by AnotherButler** [comment]
We have this information in our detailed tutorial about using the Online Compiler: https://os-doc-builder.test.mbed.com/docs/development/tutorials/forking-a-repository.html

I don't know that we need to duplicate it in the quick start, which is supposed to be a quick introduction to Mbed OS and our tools.

**Comment by 0xc0170** [comment]
Thanks @AnotherButler 

@cargro I'll close this as resolved. Please open if this needs further work.
