### ISSUE TITLE
Blinky example export encounter several issues on VSCode

### ISSUE THREAD

**Issue by Navis-Raven** [ARMmbed/mbed-os-example-blinky#134]
Before, all of that I've installed 
VSCode, 
gcc-arm-none-eabi-7-2018-q2-update-win32-sha2,
pyOCD (with pip)
C/C++ plugin (by Microsoft)  for VSCode

And as described here https://os.mbed.com/docs/v5.9/tutorials/visual-studio-code.html

I followed these instructions: 
Exporting a project/Online Compiler
Configuring the debugger

But at this step "Open the .vscode/launch.json file"
(1) There is the first problem:
There is no .vscode folder launch.json is outside the folder. 

I pushed F5 key to debug, in order to let the VSCode program create this folder. And I replaced the created lauch.json file, by ours. It solved the problems of compilation. 

I continued following the steps until "Debugging your project"

(2) Here is the second issue, and it is in the documentation : 
![image](https://user-images.githubusercontent.com/15887222/44128145-9bc384fa-a041-11e8-84da-3053f1328d87.png)

But there is no debug tab by default ! 
![image](https://user-images.githubusercontent.com/15887222/44128170-c54a386e-a041-11e8-9556-0be2a93dfdb3.png)

You'have to click on view then Debug to make it appear. 

After this I clicked on the triangle of the debug tab as explained (equivalent of F5), then third issue occurs !

(3) It says that make.exe is unfoundable: 
![image](https://user-images.githubusercontent.com/15887222/44128610-332a660e-a044-11e8-874e-badd0f90495e.png)

I remind that I've already installed GNU GCC tools for arm and added them to the PATH, like this: 
![image](https://user-images.githubusercontent.com/15887222/44128794-1a737654-a045-11e8-9afc-df2f9ca1be2a.png)

So here I'm blocked, I don't kown how to go further. 

(4) The fourth problem is that : On the getting started file
![2018-08-15 03_25_10-gettingstarted html - notuptodate](https://user-images.githubusercontent.com/15887222/44127986-7fc8d3c8-a040-11e8-9cf5-6358d8d11406.png)

When you click on this : https://os.mbed.com/docs/v5.6/tools/exporting.html/

You get this : 
![image](https://user-images.githubusercontent.com/15887222/44128054-f1f9ee50-a040-11e8-8a74-2d7e58afd598.png)

(5) The other remark is it is the 5.6 version, and it is not up to date. 

(6) I don't know even after making the json file at the good place, I still have these dependancy warnings:
![image](https://user-images.githubusercontent.com/15887222/44129031-8dc7e03a-a046-11e8-9372-36cb7662c05e.png)

**Comment by Navis-Raven** [comment]
So we have about 6 issues here at once !

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1522

**Comment by 0xc0170** [comment]
`make` is not part of GCC ARM installation. You need to have that installed separately.

Other issues seems like a problem in the documentation and vs code exporter itself

@janjongboom Can you review?

**Comment by janjongboom** [comment]
@0xc0170  Indeed Make is not part of GCC. If the '.vscode' folder is not present then that's a bug in the exporter, because it needs to have created this. @theotherjimmy

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by Navis-Raven** [comment]
@0xc0170  what's new about this bug ?

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by janjongboom** [comment]
For anyone running into this issue, https://github.com/janjongboom/mbed-vscode-generator generates vscode templates that do not require make.

**Comment by Navis-Raven** [comment]
@janjongboom  personnall I used platformIO 

But this bug must be solved for any newcommer that doesn't know how to manage these problems.

**Comment by Navis-Raven** [comment]
@adbridge  the automated bot closed it again...
