### ISSUE TITLE
the .gitignore file is outdated

### ISSUE THREAD

**Issue by JojoS62** [ARMmbed/mbed-os-example-blinky#195]
the .gitignore file contains historical path names, it should contain
```
BUILD
mbed-os
*.py*
```

this should be checked in other examples too.

**Comment by 0xc0170** [comment]
Thanks for raising this , we shall update all examples

**Comment by 0xc0170** [comment]
This would be my proposal:

```
# Default Build Directory
.build/
BUILD/
.mbed
venv/

# mbed build system
mbed-os/
mbed_settings.py
mbed_config.h
*.pyc

# exporters 
GettingStarted.html
```

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCORE-1403*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.
