### ISSUE TITLE
Please update mbed-os to have stdio baud rate configurable

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-os-example-blinky#23]

**Comment by markus-becker-tridonic-com** [comment]
I think it is mostly this issue: https://github.com/ARMmbed/mbed-os/issues/1969 and the related 9600 occurences: https://github.com/ARMmbed/mbed-os/search?utf8=%E2%9C%93&q=serial_baud%28obj%2C+9600&type=Code

**Comment by 0xc0170** [comment]
@markus-becker-tridonic-com the best would be to move this to mbed-os repo. What's your target device? 
we shall clean all of targets.

**Comment by markus-becker-tridonic-com** [comment]
NUCLEO_F401RE, NUCLEO_F091RC and K64F.

Are you able to transfer this issue. Or shall I re-create?

**Comment by 0xc0170** [comment]
Please recreate, provide a simple code snippet to reproduce. Thanks

**Comment by markus-becker-tridonic-com** [comment]
Moved to https://github.com/ARMmbed/mbed-os/issues/2396
