### ISSUE TITLE
Compile main.cpp failed as an test case for (K64F, GCC_ARM)

### ISSUE THREAD

**Issue by RdaZhongyao** [ARMmbed/mbed-os-example-blinky#28]
I need a blinky test case without greentea, so create a new case "mbed-os/TESTS/integration/blinky", and copy `mbed-os-example-blinky/main.cpp` to `mbed-os-example-blinky/mbed-os/TESTS/integration/blinky/main.cpp`, then compile this case, get error:

```
...
Compile: main.cpp
[Error] main.cpp@10,9: 'Thread' has not been declared
```

After adding this:

``` c
#include "rtos.h"
```

no error exists.

Q:
Same file "main.cpp", different compiling methods get different results:
- Example "blinky" [no error]
  - file: `mbed-os-example-blinky/main.cpp`
  - cmd:

```
mbed compile -t GCC_ARM -m K64F --source ./
```
- Test case "blinky" [error]
  - file: `mbed-os-example-blinky/mbed-os/TESTS/integration/blinky/main.cpp`
  - cmd:

```
$ mbed test -t GCC_ARM -m K64F --compile  --source ./mbed-os -n TESTS-integration-blinky
```

 @sg-  modified main.cpp at reversion ef00724, removed  `#include "rtos.h"`. That's ok for example, but as a test case, `rtos.h` has to be included. Anyone knows what happened?

**Comment by 0xc0170** [comment]
Is this still relevant?
