### ISSUE TITLE
mbed export -m K64F -i IAR

### ISSUE THREAD

**Issue by jsplyy** [ARMmbed/mbed-os-example-blinky#32]
it export iar project but compile fail.
![image 2](https://cloud.githubusercontent.com/assets/3600912/18621744/198e192e-7e5a-11e6-87ea-dbe0ea945e16.png)

**Comment by 0xc0170** [comment]
@jsplyy 

Please provide more details, version of mbed-cli, mbed-os (is it from this master?), IAR version. Any valuable info that helps us to reproduce the problem

**Comment by jsplyy** [comment]
mbed -cli 0.9.1
iar 7.4
mbedos example blinky

**Comment by 0xc0170** [comment]
This should be now resolved.  In case it's not ,please report
