### ISSUE TITLE
[OOB mbed-os-5.4] Doesn't run when compiled with IAR for target MTS-mDot-F411

### ISSUE THREAD

**Issue by mray19027** [ARMmbed/mbed-os-example-blinky#45]
Does not execute - LED1 won't light up
mbed-os version: 5.4 (OOB)
Target: MTS-mDot-F411
Toolchain: IAR

**Comment by janjongboom** [comment]
Hi @mray19027, could you report this issues against [mbed-os](https://github.com/armmbed/mbed-os)? Core engineering team does not look at this repo.

**Comment by MarceloSalazar** [comment]
Issue fixed here https://github.com/ARMmbed/mbed-os/pull/3875 and should be available in mbed OS 5.4.1

**Comment by 0xc0170** [comment]
Since 5.4.1, this export wont be allowed.

**Comment by janjongboom** [comment]
Also Multitech only provides blobs of their LoRa MAC layer for GCC and ARMCC, so IAR was always a bit useless.
