### ISSUE TITLE
Delay too long on LPC1768 with default GCC profile

### ISSUE THREAD

**Issue by baijund** [ARMmbed/mbed-os-example-blinky#78]
When compiling using the default (develop) profile on the mbed cli, the LED toggles every ~5 seconds instead of the desired 0.5 seconds. When building using the debug profile, the program functions as expected. This is using the GCC toolchain.

**Comment by 0xc0170** [comment]
This might be related - https://github.com/ARMmbed/mbed-os/issues/4815 ?

**Comment by baijund** [comment]
Updating the FW fixed the issue. Thanks!
