### ISSUE TITLE
Compilation failure with IAR 8 with NUCLEO_F429ZI target

### ISSUE THREAD

**Issue by vijhar01** [ARMmbed/mbed-os-example-blinky#83]
**PS C:\Users\vijhar01\mbed-os-example-blinky> mbed detect**

[mbed] Detected NUCLEO_F429ZI, port COM6, mounted D:
[mbed] Supported toolchains for NUCLEO_F429ZI
+---------------+-----------+-----------+-----------+-----------+-----------+
| Target        | mbed OS 2 | mbed OS 5 |    ARM    |  GCC_ARM  |    IAR    |
+---------------+-----------+-----------+-----------+-----------+-----------+
| NUCLEO_F429ZI | Supported | Supported | Supported | Supported | Supported |
+---------------+-----------+-----------+-----------+-----------+-----------+
Supported targets: 1
Supported toolchains: 3

**PS C:\Users\vijhar01\mbed-os-example-blinky> mbed compile -t IAR -m NUCLEO_F429ZI**
Building project mbed-os-example-blinky (NUCLEO_F429ZI, IAR)
Scan: .
Scan: mbed
Scan: env
Scan: FEATURE_LWIP
Compile [  0.2%]: cmain.S
Compile [  0.5%]: AnalogIn.cpp
Compile [  0.7%]: BusIn.cpp
Compile [  1.0%]: BusInOut.cpp
Compile [  1.2%]: main.cpp
Compile [  1.5%]: Ethernet.cpp
Compile [  1.7%]: BusOut.cpp
Compile [  2.0%]: CAN.cpp
Compile [  2.2%]: FlashIAP.cpp
Compile [  2.5%]: I2CSlave.cpp
Compile [  2.7%]: I2C.cpp
Compile [  3.0%]: InterruptIn.cpp
Compile [  3.2%]: InterruptManager.cpp
Compile [  3.5%]: RawSerial.cpp
Compile [  3.7%]: SPISlave.cpp
Compile [  4.0%]: SPI.cpp
Compile [  4.2%]: Serial.cpp
Compile [  4.5%]: SerialBase.cpp
Compile [  4.7%]: Ticker.cpp
Compile [  5.0%]: Timeout.cpp
Compile [  5.2%]: TimerEvent.cpp
Compile [  5.5%]: Timer.cpp
Compile [  5.7%]: UARTSerial.cpp
Compile [  6.0%]: equeue.c
Compile [  6.2%]: EventQueue.cpp
Compile [  6.5%]: equeue_mbed.cpp
Compile [  6.7%]: emac_lwip.c
Compile [  7.0%]: emac_stack_lwip.cpp
Compile [  7.2%]: equeue_posix.c
Compile [  7.5%]: stm32f4_eth_conf.c
Compile [  7.7%]: stm32f4_eth_init.c
Compile [  8.0%]: lwip_checksum.c
Compile [  8.2%]: lwip_memcpy.c
Compile [  8.5%]: EthernetInterface.cpp
Compile [  8.7%]: stm32xx_emac.c
[Warning] stm32xx_emac.c@98,24: [Pe177]: variable "regvalue" was declared but never referenced
[Warning] stm32xx_emac.c@99,0: [Pe550]: variable "hal_eth_init_status" was set but never used
Compile [  9.0%]: lwip_random.c
Compile [  9.2%]: lwip_sys_arch.c
Compile [  9.5%]: lwip_tcp_isn.c
Compile [  9.7%]: lwip_api_lib.c
Compile [ 10.0%]: lwip_err.c
Compile [ 10.2%]: lwip_api_msg.c
Compile [ 10.5%]: lwip_netdb.c
Compile [ 10.7%]: lwip_netifapi.c
Compile [ 11.0%]: lwip_netbuf.c
Compile [ 11.2%]: lwip_sockets.c
Compile [ 11.5%]: lwip_autoip.c
Compile [ 11.7%]: lwip_tcpip.c
Compile [ 12.0%]: lwip_icmp.c
Compile [ 12.2%]: lwip_etharp.c
Compile [ 12.5%]: lwip_dhcp.c
Compile [ 12.7%]: lwip_igmp.c
Compile [ 13.0%]: lwip_ip4_addr.c
Compile [ 13.2%]: lwip_ip4.c
Compile [ 13.5%]: lwip_dhcp6.c
Compile [ 13.7%]: lwip_ip4_frag.c
Compile [ 14.0%]: lwip_ethip6.c
Compile [ 14.2%]: lwip_icmp6.c
Compile [ 14.5%]: lwip_inet6.c
Compile [ 14.7%]: lwip_ip6.c
Compile [ 15.0%]: lwip_ip6_addr.c
Compile [ 15.2%]: lwip_mld6.c
Compile [ 15.5%]: lwip_ip6_frag.c
Compile [ 15.7%]: lwip_nd6.c
Compile [ 16.0%]: lwip_def.c
Compile [ 16.2%]: lwip_inet_chksum.c
Compile [ 16.5%]: lwip_dns.c
Compile [ 16.7%]: lwip_ip.c
Compile [ 17.0%]: lwip_init.c
[Warning] lwip_init.c@344,0: [Pe549]: variable "a" is used before its value is set
Compile [ 17.2%]: lwip_mem.c
Compile [ 17.5%]: lwip_memp.c
Compile [ 17.7%]: lwip_raw.c
Compile [ 18.0%]: lwip_netif.c
Compile [ 18.2%]: lwip_pbuf.c
Compile [ 18.5%]: lwip_stats.c
Compile [ 18.7%]: lwip_sys.c
Compile [ 19.0%]: lwip_tcp.c
Compile [ 19.2%]: lwip_tcp_in.c
Compile [ 19.5%]: lwip_timeouts.c
Compile [ 19.7%]: lwip_tcp_out.c
Compile [ 20.0%]: lwip_ethernetif.c
Compile [ 20.2%]: lwip_ethernet.c
Compile [ 20.4%]: lwip_udp.c
Compile [ 20.7%]: lwip_lowpan6.c
Compile [ 20.9%]: lwip_auth.c
Compile [ 21.2%]: lwip_chap-md5.c
Compile [ 21.4%]: lwip_ccp.c
Compile [ 21.7%]: lwip_chap-new.c
Compile [ 21.9%]: lwip_chap_ms.c
Compile [ 22.2%]: lwip_demand.c
Compile [ 22.4%]: lwip_ecp.c
Compile [ 22.7%]: lwip_eap.c
Compile [ 22.9%]: lwip_eui64.c
Compile [ 23.2%]: lwip_fsm.c
Compile [ 23.4%]: lwip_ipcp.c
Compile [ 23.7%]: lwip_ipv6cp.c
Compile [ 23.9%]: lwip_magic.c
Compile [ 24.2%]: lwip_lcp.c
Compile [ 24.4%]: lwip_mppe.c
Compile [ 24.7%]: lwip_multilink.c
Compile [ 24.9%]: lwip_pppapi.c
Compile [ 25.2%]: lwip_ppp.c
Compile [ 25.4%]: lwip_pppcrypt.c
Compile [ 25.7%]: lwip_pppoe.c
Compile [ 25.9%]: lwip_upap.c
Compile [ 26.2%]: lwip_pppol2tp.c
Compile [ 26.4%]: lwip_pppos.c
Compile [ 26.7%]: lwip_utils.c
Compile [ 26.9%]: lwip_vj.c
Compile [ 27.2%]: lwip_arc4.c
Compile [ 27.4%]: lwip_des.c
Compile [ 27.7%]: lwip_md4.c
Compile [ 27.9%]: lwip_md5.c
Compile [ 28.2%]: lwip_sha1.c
Compile [ 28.4%]: ppp_lwip.cpp
Compile [ 28.7%]: Dir.cpp
Compile [ 28.9%]: lwip_stack.c
[Warning] lwip_stack.c@583,18: [Pe174]: expression has no effect
[Warning] lwip_stack.c@609,0: [Pe174]: expression has no effect
Compile [ 29.2%]: File.cpp
Compile [ 29.4%]: FileSystem.cpp
Compile [ 29.7%]: HeapBlockDevice.cpp
Compile [ 29.9%]: ChainingBlockDevice.cpp
Compile [ 30.2%]: MBRBlockDevice.cpp
Compile [ 30.4%]: ccsbcs.cpp
Compile [ 30.7%]: ProfilingBlockDevice.cpp
Compile [ 30.9%]: SlicingBlockDevice.cpp
Compile [ 31.2%]: FATFileSystem.cpp
Compile [ 31.4%]: greentea_serial.cpp
Compile [ 31.7%]: greentea_metrics.cpp
Compile [ 31.9%]: ff.cpp
Compile [ 32.2%]: unity.c
Compile [ 32.4%]: greentea_test_env.cpp
Compile [ 32.7%]: mbed-utest-shim.cpp
Compile [ 32.9%]: unity_handler.cpp
Compile [ 33.2%]: utest_case.cpp
Compile [ 33.4%]: utest_default_handlers.cpp
Compile [ 33.7%]: utest_greentea_handlers.cpp
Compile [ 33.9%]: utest_stack_trace.cpp
Compile [ 34.2%]: mbed_trng.c
Compile [ 34.4%]: utest_harness.cpp
[Warning] utest_harness.cpp@210,0: [Pe111]: statement is unreachable
Compile [ 34.7%]: utest_shim.cpp
Compile [ 34.9%]: aesni.c
Compile [ 35.2%]: arc4.c
Compile [ 35.4%]: utest_types.cpp
Compile [ 35.7%]: asn1parse.c
Compile [ 35.9%]: asn1write.c
Compile [ 36.2%]: base64.c
Compile [ 36.4%]: aes.c
Compile [ 36.7%]: blowfish.c
Compile [ 36.9%]: camellia.c
Compile [ 37.2%]: certs.c
Compile [ 37.4%]: ccm.c
Compile [ 37.7%]: cipher_wrap.c
Compile [ 37.9%]: cipher.c
Compile [ 38.2%]: cmac.c
Compile [ 38.4%]: des.c
Compile [ 38.7%]: dhm.c
Compile [ 38.9%]: ctr_drbg.c
Compile [ 39.2%]: debug.c
Compile [ 39.4%]: ecdh.c
Compile [ 39.7%]: ecjpake.c
Compile [ 39.9%]: ecdsa.c
Compile [ 40.1%]: entropy.c
Compile [ 40.4%]: bignum.c
Compile [ 40.6%]: entropy_poll.c
Compile [ 40.9%]: ecp_curves.c
Compile [ 41.1%]: havege.c
Compile [ 41.4%]: hmac_drbg.c
Compile [ 41.6%]: gcm.c
Compile [ 41.9%]: md2.c
Compile [ 42.1%]: md.c
Compile [ 42.4%]: ecp.c
Compile [ 42.6%]: md4.c
Compile [ 42.9%]: md5.c
Compile [ 43.1%]: md_wrap.c
Compile [ 43.4%]: memory_buffer_alloc.c
Compile [ 43.6%]: net_sockets.c
Compile [ 43.9%]: padlock.c
Compile [ 44.1%]: pem.c
Compile [ 44.4%]: oid.c
Compile [ 44.6%]: pk.c
Compile [ 44.9%]: pkcs11.c
Compile [ 45.1%]: pk_wrap.c
Compile [ 45.4%]: pkcs12.c
Compile [ 45.6%]: pkcs5.c
Compile [ 45.9%]: platform.c
Compile [ 46.1%]: pkwrite.c
Compile [ 46.4%]: error.c
Compile [ 46.6%]: ripemd160.c
Compile [ 46.9%]: pkparse.c
Compile [ 47.1%]: sha1.c
Compile [ 47.4%]: ssl_cache.c
Compile [ 47.6%]: ssl_ciphersuites.c
Compile [ 47.9%]: sha256.c
Compile [ 48.1%]: sha512.c
Compile [ 48.4%]: rsa.c
Compile [ 48.6%]: ssl_cookie.c
Compile [ 48.9%]: ssl_ticket.c
Compile [ 49.1%]: threading.c
Compile [ 49.4%]: timing.c
Compile [ 49.6%]: version.c
Compile [ 49.9%]: version_features.c
Compile [ 50.1%]: ssl_cli.c
Compile [ 50.4%]: x509.c
Compile [ 50.6%]: x509_create.c
Compile [ 50.9%]: ssl_srv.c
[Warning] ssl_srv.c@2689,0: [Pe549]: variable "len" is used before its value is set
Compile [ 51.1%]: x509_crl.c
Compile [ 51.4%]: x509_csr.c
Compile [ 51.6%]: x509write_crt.c
Compile [ 51.9%]: x509write_csr.c
Compile [ 52.1%]: xtea.c
Compile [ 52.4%]: aes_alt.c
Compile [ 52.6%]: md5_alt.c
Compile [ 52.9%]: sha1_alt.c
Compile [ 53.1%]: sha256_alt.c
Compile [ 53.4%]: NetworkInterface.cpp
Compile [ 53.6%]: x509_crt.c
Compile [ 53.9%]: ssl_tls.c
Compile [ 54.1%]: NetworkStack.cpp
Compile [ 54.4%]: Socket.cpp
Compile [ 54.6%]: SocketAddress.cpp
Compile [ 54.9%]: TCPServer.cpp
Compile [ 55.1%]: WiFiAccessPoint.cpp
Compile [ 55.4%]: OnboardCellularInterface.cpp
Compile [ 55.6%]: TCPSocket.cpp
Compile [ 55.9%]: UDPSocket.cpp
Compile [ 56.1%]: mbed_flash_api.c
Compile [ 56.4%]: PPPCellularInterface.cpp
Compile [ 56.6%]: UARTCellularInterface.cpp
Compile [ 56.9%]: nsapi_dns.cpp
Compile [ 57.1%]: mbed_gpio.c
Compile [ 57.4%]: mbed_pinmap_common.c
Compile [ 57.6%]: mbed_lp_ticker_api.c
Compile [ 57.9%]: mbed_ticker_api.c
Compile [ 58.1%]: mbed_us_ticker_api.c
Compile [ 58.4%]: CallChain.cpp
Compile [ 58.6%]: FileBase.cpp
Compile [ 58.9%]: FileHandle.cpp
Compile [ 59.1%]: ATCmdParser.cpp
Compile [ 59.4%]: FilePath.cpp
Compile [ 59.6%]: LocalFileSystem.cpp
Compile [ 59.9%]: FileSystemHandle.cpp
Compile [ 60.1%]: mbed_alloc_wrappers.cpp
Compile [ 60.3%]: Stream.cpp
Compile [ 60.6%]: mbed_application.c
Compile [ 60.8%]: mbed_assert.c
Compile [ 61.1%]: mbed_board.c
Compile [ 61.3%]: mbed_error.c
Compile [ 61.6%]: mbed_critical.c
Compile [ 61.8%]: mbed_mktime.c
Compile [ 62.1%]: mbed_mem_trace.c
Compile [ 62.3%]: mbed_interface.c
Compile [ 62.6%]: mbed_poll.cpp
Compile [ 62.8%]: mbed_sdk_boot.c
Compile [ 63.1%]: mbed_rtc_time.cpp
Compile [ 63.3%]: mbed_retarget.cpp
[Error] mbed_retarget.cpp@850,47: [Pe393]: pointer to incomplete class type is not allowed
[Error] mbed_retarget.cpp@850,15: [Pe393]: pointer to incomplete class type is not allowed
[Error] mbed_retarget.cpp@851,30: [Pe393]: pointer to incomplete class type is not allowed
[Error] mbed_retarget.cpp@851,15: [Pe393]: pointer to incomplete class type is not allowed
[Error] mbed_retarget.cpp@852,30: [Pe393]: pointer to incomplete class type is not allowed
[Error] mbed_retarget.cpp@852,15: [Pe393]: pointer to incomplete class type is not allowed
[Error] mbed_retarget.cpp@865,47: [Pe393]: pointer to incomplete class type is not allowed
[Error] mbed_retarget.cpp@865,15: [Pe393]: pointer to incomplete class type is not allowed
[Error] mbed_retarget.cpp@866,30: [Pe393]: pointer to incomplete class type is not allowed
[Error] mbed_retarget.cpp@866,15: [Pe393]: pointer to incomplete class type is not allowed
[Error] mbed_retarget.cpp@867,30: [Pe393]: pointer to incomplete class type is not allowed
[Error] mbed_retarget.cpp@867,0: [Pe393]: pointer to incomplete class type is not allowed
[ERROR]
          _file->_Mode = (unsigned short)(_file->_Mode & ~ 0x1000);/* Unset read mode */
               ^
"C:\Users\vijhar01\mbed-os-example-blinky\mbed-os\platform\mbed_retarget.cpp",850  Error[Pe393]: pointer to incomplete c
lass type is not allowed

          _file->_Mode = (unsigned short)(_file->_Mode & ~ 0x1000);/* Unset read mode */
                                               ^
"C:\Users\vijhar01\mbed-os-example-blinky\mbed-os\platform\mbed_retarget.cpp",850  Error[Pe393]: pointer to incomplete c
lass type is not allowed

          _file->_Rend = _file->_Wend;
               ^
"C:\Users\vijhar01\mbed-os-example-blinky\mbed-os\platform\mbed_retarget.cpp",851  Error[Pe393]: pointer to incomplete c
lass type is not allowed

          _file->_Rend = _file->_Wend;
                              ^
"C:\Users\vijhar01\mbed-os-example-blinky\mbed-os\platform\mbed_retarget.cpp",851  Error[Pe393]: pointer to incomplete c
lass type is not allowed

          _file->_Next = _file->_Wend;
               ^
"C:\Users\vijhar01\mbed-os-example-blinky\mbed-os\platform\mbed_retarget.cpp",852  Error[Pe393]: pointer to incomplete c
lass type is not allowed

          _file->_Next = _file->_Wend;
                              ^
"C:\Users\vijhar01\mbed-os-example-blinky\mbed-os\platform\mbed_retarget.cpp",852  Error[Pe393]: pointer to incomplete c
lass type is not allowed

          _file->_Mode = (unsigned short)(_file->_Mode & ~ 0x1000);/* Unset read mode */
               ^
"C:\Users\vijhar01\mbed-os-example-blinky\mbed-os\platform\mbed_retarget.cpp",865  Error[Pe393]: pointer to incomplete c
lass type is not allowed

          _file->_Mode = (unsigned short)(_file->_Mode & ~ 0x1000);/* Unset read mode */
                                               ^
"C:\Users\vijhar01\mbed-os-example-blinky\mbed-os\platform\mbed_retarget.cpp",865  Error[Pe393]: pointer to incomplete c
lass type is not allowed

          _file->_Rend = _file->_Wend;
               ^
"C:\Users\vijhar01\mbed-os-example-blinky\mbed-os\platform\mbed_retarget.cpp",866  Error[Pe393]: pointer to incomplete c
lass type is not allowed

          _file->_Rend = _file->_Wend;
                              ^
"C:\Users\vijhar01\mbed-os-example-blinky\mbed-os\platform\mbed_retarget.cpp",866  Error[Pe393]: pointer to incomplete c
lass type is not allowed

          _file->_Next = _file->_Wend;
               ^
"C:\Users\vijhar01\mbed-os-example-blinky\mbed-os\platform\mbed_retarget.cpp",867  Error[Pe393]: pointer to incomplete c
lass type is not allowed

          _file->_Next = _file->_Wend;
                              ^
"C:\Users\vijhar01\mbed-os-example-blinky\mbed-os\platform\mbed_retarget.cpp",867  Error[Pe393]: pointer to incomplete c
lass type is not allowed

[mbed] ERROR: "C:\Python27\python.exe" returned error code 1.
[mbed] ERROR: Command "C:\Python27\python.exe -u C:\Users\vijhar01\mbed-os-example-blinky\mbed-os\tools\make.py -t IAR -
m NUCLEO_F429ZI --source . --build .\BUILD\NUCLEO_F429ZI\IAR" in "C:\Users\vijhar01\mbed-os-example-blinky"
---

**Comment by MarceloSalazar** [comment]
cc @adbridge

**Comment by adbridge** [comment]
Strange this build in the pr for IAR 8 - 
```
Compile [ 64.9%]: mbed_retarget.cpp
[DEBUG] Compile: C:\Program Files (x86)\IAR Systems\Embedded Workbench 8.0\arm\bin\iccarm --no_wrap_diagnostics -e --diag_suppress=Pa050,Pa084,Pa093,Pa082 -Oh --cpu Cortex-M4F --thumb --dlib_config DLib_Config_Full.h --c++ --no_rtti --no_exceptions --guard_calls --no_static_destruction -DTARGET_STM32F429xx -DDEVICE_SPISLAVE=1 -DFEATURE_LWIP=1 -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 -DTRANSACTION_QUEUE_SIZE_SPI=2 -DUSBHOST_OTHER -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DTARGET_NUCLEO_F429ZI -DDEVICE_LOWPOWERTIMER=1 -DDEVICE_RTC=1 -DTOOLCHAIN_object -DTARGET_STM32F4 -D__CMSIS_RTOS -DDEVICE_CAN=1 -DTARGET_CORTEX_M -DDEVICE_I2C_ASYNCH=1 -DTARGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 -DTARGET_UVISOR_UNSUPPORTED -DDEVICE_PORTOUT=1 -DDEVICE_SPI_ASYNCH=1 -DTOOLCHAIN_IAR -DDEVICE_INTERRUPTIN=1 -DTARGET_CORTEX -DDEVICE_I2C=1 -DTARGET_STM32F429 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 -DDEVICE_PWMOUT=1 -DTARGET_FAMILY_STM32 -DTARGET_FF_ARDUINO -DDEVICE_PORTIN=1 -DTARGET_RELEASE -DTARGET_STM -DDEVICE_SERIAL_FC=1 -DDEVICE_TRNG=1 -DTARGET_LIKE_MBED -DTARGET_STM32F429ZI -D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DDEVICE_SPI=1 -DUSB_STM_HAL -DTARGET_STM32F429xI -DDEVICE_ANALOGIN=1 -DDEVICE_SERIAL=1 -DDEVICE_FLASH=1 -DARM_MATH_CM4 -DMBED_BUILD_TIMESTAMP=1505080586.76 -f .\BUILD\NUCLEO_F429ZI\IAR\.includes_82eefb55eda86348fecbc5857b0d13b6.txt --preinclude=.\BUILD\NUCLEO_F429ZI\IAR\mbed_config.h --dependencies .\BUILD\NUCLEO_F429ZI\IAR\mbed-os\platform\mbed_retarget.d -l .\BUILD\NUCLEO_F429ZI\IAR\mbed-os\platform\mbed_retarget.s.txt -o .\BUILD\NUCLEO_F429ZI\IAR\mbed-os\platform\mbed_retarget.o .\mbed-os\platform\mbed_retarget.cpp
[DEBUG] Return: 0
Compile [ 65.1%]: RTX_Config.c
```

**Comment by adbridge** [comment]
@vijhar01  What platform did you build on and what exact version of IAR did you use?

**Comment by adbridge** [comment]
I have just reproduced this using the windows version of IAR workbench - 
IAR ANSI C/C++ Compiler V8.11.3.13950/W32 for ARM
Running in gitbash on windows 10.

@shrikant I assume we are running the linux version in the ci ?

**Comment by vijhar01** [comment]
Hi Anna,

Here are my test environment details:

Build environment – Windows 10
IAR version - 8.11.2.13589 (8.11.2.13589)

Thanks, Viji

**Comment by adbridge** [comment]
I've built with latest mbed-os master and that builds ok!

**Comment by adbridge** [comment]
mmm ok so I now did this - 
> rm -rf mbed-os/                                                                                                                                                                            
> mbed deploy                                                                                                                                                                                
[mbed] Adding library "mbed-os" from "https://github.com/ARMmbed/mbed-os" at rev #a4056fb8bf3e                                                                                               
> mbed compile -t IAR -m NUCLEO_F429ZI            

and this worked for me. 
The first time I tried it I did not remove the previous mbed-os. I'm wondering if you had leftover artifacts ?

@vijhar01 Could you please re-try this but following the above steps ?

**Comment by vijhar01** [comment]
That worked.
I was able to compile successfully with IAR

Documentation enhancement:

Publish examples for export into iar 8 workspace.

I ran the following and did not know where to look for the exported iar project

C:\mbed-os-example-blinky> mbed export -m NUCLEO_F429ZI -i IAR
Scan: .
Scan: FEATURE_LWIP
PS C:\mbed-os-example-blinky>

I found an mbed-os-example-blinky.eww file in the current directory and was able to open it in the IAR workbench. I hope that is the right file.

Thanks, Viji

**Comment by MarceloSalazar** [comment]
> Documentation enhancement:
> Publish examples for export into iar 8 workspace.
> I ran the following and did not know where to look for the exported iar project

@AnotherButler FYI find here some feedback on docs for exporters

**Comment by AnotherButler** [comment]
Thanks for letting me know @MarceloSalazar I've created a JIRA issue for this.
