### ISSUE TITLE
Blinky example should print something

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/mbed-os-example-blinky#96]
As there are multiple boards that do not actually have an user controllable LED, those should just print "Blink!" or something - or actually all boards could print something, say every 10 times it's blinked the (imaginary) LED.

**Comment by 0xc0170** [comment]
Can you list those boards please?

**Comment by JanneKiiskila** [comment]
Well, try out the REALTEK_RTL8195AM for example.

It has plenty of LEDs, just none of the seem to be available for the "user" side.

**Comment by JanneKiiskila** [comment]
PR created; https://github.com/ARMmbed/mbed-os-example-blinky/pull/97

**Comment by JanneKiiskila** [comment]
Raised also an issue towards Realtek; https://github.com/ARMmbed/mbed-os/issues/5642

**Comment by 0xc0170** [comment]
Realtek fixed their documentation, this should be resolved. This example blinks only

Thanks for the report for realtek
